apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certificates/kibana.crt
    server.ssl.key: /usr/share/kibana/config/certificates/kibana.key
    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.6.0
          ports:
            - containerPort: 5601
              name: http
          volumeMounts:
            - name: config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: certificates
              mountPath: /usr/share/kibana/config/certificates
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
        - name: certificates
          secret:
            secretName: kibana-tls

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
spec:
  selector:
    app: kibana
  ports:
    - name: posts
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30360
  type: NodePort
