apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: elk
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/pods/*/*/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type record_transformer
      <record>
        namespace ${record["kubernetes"]["namespace_name"]}
        pod_name ${record["kubernetes"]["pod_name"]}
      </record>
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      hosts ["http://uspgh-neks-p10.amer.thermo.com:31500", "http://uspgh-neks-p11.amer.thermo.com:31500", "http://uspgh-neks-p12.amer.thermo.com:31500"]
      index_name onprem-kube-dev-os-mon-log-request-breakdown-000001
      ssl_verify false
      template_name onprem-kube-dev-os-mon-log-request-breakdown-000001
      template_pattern onprem-kube-dev-os-mon-log-request-breakdown-000001
      ilm_policy_id onprem-kube-dev-os-mon-log-request-breakdown-000001
      ilm_policy_overwrite true
      <buffer>
        flush_interval 5s
      </buffer>
    </match>

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elk
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch7
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluentd-config
              mountPath: /fluentd/etc/
              subPath: fluent.conf
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluentd-config
          configMap:
            name: fluentd-config
