apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
          - /var/log/containers/*_globalgateway_*.log
        multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
        multiline.negate: false
        multiline.match: after
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts:
        - "http://uspgh-neks-p10.amer.thermo.com:31500"
        - "http://uspgh-neks-p11.amer.thermo.com:31500"
        - "http://uspgh-neks-p12.amer.thermo.com:31500"
      index: "onprem-kube-dev-os-mon-log-request-breakdown-000001"

    setup.kibana:
      host: "10.0.146.250:5601"

    setup.template.name: "onprem-kube-dev-os-mon-log-request-breakdown-000001"
    setup.template.pattern: "onprem-kube-dev-os-mon-log-request-breakdown-000001"
    setup.ilm.overwrite: true
    setup.ilm.enabled: false


    filebeat.config.modules:
      path: /etc/filebeat/modules.d/*.yml
      reload.enabled: false

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat-sa
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.9.0
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_PTRACE"]
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/log/containers
            - name: pods
              mountPath: /var/log/pods
            - name: docker
              mountPath: /var/lib/docker/containers
      volumes:
        - name: config
          configMap:
            name: filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: elk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-role-binding
roleRef:
  kind: ClusterRole
  name: filebeat-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: filebeat-sa
    namespace: elk

