---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        stream: all
        close_inactive: 1h  # Prevents closing active logs too soon
        ignore_older: 24h   # Ignore logs older than 24h
        scan_frequency: 10s  # Scan logs every 10 seconds
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
          - drop_event:
              when:
                not:
                  equals:
                    kubernetes.namespace: "globalgateway"  # Filter logs only for globalgateway namespace

    output.elasticsearch:
      hosts: 
        - "http://uspgh-neks-p10.amer.thermo.com:31500"
        - "http://uspgh-neks-p11.amer.thermo.com:31500"
        - "http://uspgh-neks-p12.amer.thermo.com:31500"
      bulk_max_size: 500
      worker: 2
      index: "onprem-kube-dev-os-mon-log-request-breakdown-000001"

    setup.kibana:
      host: "10.0.146.250:5601"

    setup.template.name: "onprem-kube-dev-os-mon-log-request-breakdown"
    setup.template.pattern: "onprem-kube-dev-os-mon-log-request-breakdown-*"
    setup.template.settings:
      index.number_of_shards: 1
      index.number_of_replicas: 1
    setup.ilm.enabled: false

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*-*.log
          processors:
            - add_kubernetes_metadata:
                in_cluster: true

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.9.0
          securityContext:
            runAsUser: 0
            fsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_PTRACE"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: filebeat-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: elk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
      - pods/log
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: elk
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
