apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          include_annotations: ["artifact.spinnaker.io/name", "ad.datadoghq.com/tags"]
          include_labels: ["app.kubernetes.io/name"]
          labels.dedot: true
          annotations.dedot: true
          templates:
            - condition:
                equals:
                  kubernetes.namespace: myapp
              config:
                - type: container
                  paths:
                    - /var/log/pods/*/*/*.log
                  multiline:
                    pattern: '^[A-Za-z]+ [0-9]{1,2} (?:[01]\d|2[0-3]):(?:[0-5]\d):(?:[0-5]\d)'
                    negate: true
                    match: after
            - condition:
                equals:
                  kubernetes.namespace: elasticsearch
              config:
                - type: container
                  paths:
                    - /var/log/pods/*/*/*.log
                  multiline:
                    pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}|^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
                    negate: true
                    match: after

    output.elasticsearch:
      hosts: ["http://uspgh-neks-p10.amer.thermo.com:31500", "http://uspgh-neks-p11.amer.thermo.com:31500", "http://uspgh-neks-p12.amer.thermo.com:31500"]
      index: "onprem-kube-dev-os-mon-log-request-breakdown-000001"

    setup.kibana:
      host: "10.0.146.250:5601"

    setup.template.name: "onprem-kube-dev-os-mon-log-request-breakdown-000001"
    setup.template.pattern: "onprem-kube-dev-os-mon-log-request-breakdown-000001"
    setup.ilm.overwrite: true

    filebeat.config.modules:
      path: /etc/filebeat/modules.d/*.yml
      reload.enabled: false

    processors:
      - add_cloud_metadata: ~
      - drop_fields:
          when:
            has_fields: ['kubernetes.labels.app']
          fields:
            - 'kubernetes.labels.app'

    logging.level: debug  # Enable debug logs for troubleshooting

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.9.0
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_PTRACE"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: filebeat-config
