apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: elk
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    # Kubernetes metadata enrichment
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    # Send logs to all Elasticsearch nodes
    <match kubernetes.**>
      @type elasticsearch
      hosts ["http://uspgh-neks-p10.amer.thermo.com:31500", "http://uspgh-neks-p11.amer.thermo.com:31500", "http://uspgh-neks-p12.amer.thermo.com:31500"]
      logstash_format true
      logstash_prefix fluentd-kubernetes
      include_tag_key true
      flush_interval 5s
    </match>

    # Configure Kibana for Fluentd
    <match kubernetes.**>
      @type copy
      <store>
        @type elasticsearch
        hosts ["http://uspgh-neks-p10.amer.thermo.com:31500", "http://uspgh-neks-p11.amer.thermo.com:31500", "http://uspgh-neks-p12.amer.thermo.com:31500"]
        logstash_format true
        logstash_prefix fluentd-kubernetes
      </store>
      <store>
        @type stdout
      </store>
    </match>

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elk
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd-sa
      terminationGracePeriodSeconds: 30
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "uspgh-neks-p10.amer.thermo.com,uspgh-neks-p11.amer.thermo.com,uspgh-neks-p12.amer.thermo.com"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "31500"
            - name: FLUENT_KIBANA_HOST
              value: "10.0.146.250:5601"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluentd.conf
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluentd-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-sa
  namespace: elk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-role
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-role-binding
subjects:
  - kind: ServiceAccount
    name: fluentd-sa
    namespace: elk
roleRef:
  kind: ClusterRole
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io
